import React from 'react';
import { ArrowRight } from 'lucide-react';

const Hero: React.FC = () => {
  return (
    <section className="pt-32 pb-20 md:pt-40 md:pb-28 bg-gradient-to-br from-purple-50 via-white to-purple-50">
      <div className="container mx-auto px-4 md:px-6">
        <div className="flex flex-col md:flex-row items-center gap-12">
          <div className="md:w-1/2 space-y-6">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-serif italic text-purple-800 font-bold leading-tight">
              Transform <span className="text-purple-900">Instagram Comments</span> Into Stunning Reviews
            </h1>
            <p className="text-lg md:text-xl text-gray-700 leading-relaxed">
              Revilo turns your best Instagram comments into beautifully designed, 
              shareable review cards with just your Instagram handle. Boost credibility and 
              engagement in seconds.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 pt-4">
              <a 
                href="https://tally.so/r/wLo0l1"
                target="_blank"
                rel="noopener noreferrer"
                className="bg-purple-700 hover:bg-purple-800 text-white px-8 py-3 rounded-full text-lg font-medium transition-all flex items-center justify-center group"
              >
                Get Started 
                <ArrowRight className="ml-2 group-hover:translate-x-1 transition-transform" size={20} />
              </a>
              <a 
                href="#how-it-works" 
                className="bg-white hover:bg-gray-100 text-purple-700 border border-purple-300 px-8 py-3 rounded-full text-lg font-medium transition-all flex items-center justify-center"
              >
                How It Works
              </a>
            </div>
          </div>
          <div className="md:w-1/2 relative">
            <div className="absolute -top-10 -left-10 w-32 h-32 bg-purple-200 rounded-full opacity-30 animate-pulse-slow"></div>
            <div className="absolute -bottom-5 -right-5 w-24 h-24 bg-purple-300 rounded-full opacity-30 animate-pulse-slow animation-delay-1000"></div>
            
            <div className="relative bg-white rounded-xl shadow-xl overflow-hidden transform transition-all hover:scale-[1.02] p-6 border border-purple-100">
              <div className="flex items-start gap-4 mb-4">
                <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center">
                  <span className="text-purple-700 font-bold">JD</span>
                </div>
                <div>
                  <h3 className="font-bold text-gray-900">Jane Doe</h3>
                  <p className="text-gray-500 text-sm">@jane • Instagram</p>
                </div>
              </div>
              <p className="text-gray-700 italic mb-4">
                "This product completely changed how I work! The interface is intuitive
                and the results are amazing. Would recommend to anyone!"
              </p>
              <div className="flex items-center justify-between">
                <div className="flex">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <svg key={star} className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  ))}
                </div>
                <span className="text-xs text-purple-600 font-medium">Generated by Revilo</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;